EasyRPG/liblcf

src/reader_struct.h
(cherry picked from commit bdcf9fd942632cf4ae2ec67c87176a50aa8dfd81)
=> Remove redundant FieldReader template

src/reader_struct.cpp
Keeps the emscripten console clean
=> Disable stdout debug messages

generator/csv/fields.csv, src/generated/ldb_chunks.h, src/generated/ldb_skill.cpp, src/generated/rpg_skill.cpp, src/generated/rpg_skill.h
I usually don't just rename variables but these naming didn't make any sense
=> Rename pdef_f to physical rate and mdef_f to magical rate

builds/vs2015/liblcf.vcxproj
Basicly just clicking a button in the GUI ^^ and defining _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1
=> MSVC: Add ARM support

src/rpg_fixup.cpp, src/rpg_setup.cpp
Will need this for my next PR of development branch.
Merging NOT recommended until my branch is ready. The states will break everything.
=> Fix states and message stretch

src/reader_util.cpp
This improves the encoding detection of translated games that use the RTP of the original language.
=> Use strings from Data::system to detect encoding

generator/csv/fields.csv, src/generated/rpg_trooppagecondition.h
=> Fix default value for TroopPageCondition->enemy_id (0, not 1)

src/reader_util.cpp, src/reader_util.h
=> Add a new function DetectEncodings that returns all detected encodings

README, builds/cmake/CMakeLists.txt, builds/liblcf.pc.in, configure.ac
=> Change homepage URL and update version to 0.5.0

generator/csv/structs.csv, src/generated/rpg_map.h
=> Don't generate ID property for LMU Map field

src/lsd_reader.cpp
As suggested by Ghabry in https://github.com/EasyRPG/Player/pull/1096#issuecomment-277565487
=> Let callers control GenerateTimestamp

generator/csv/fields.csv, src/generated/ldb_chunks.h, src/generated/ldb_troop.cpp, src/generated/rpg_troop.h
See https://github.com/EasyRPG/Player/issues/987 for more info.
=> Add 'appear_randomly' flag to Troops

generator/csv/fields.csv, src/generated/ldb_animation.cpp, src/generated/ldb_chunks.h, src/generated/rpg_animation.h
=> RPG::Animation: Rename unknown_03 to large.

generator/csv/enums.csv, generator/csv/fields.csv, src/generated/lmt_chunks.h, src/generated/rpg_treemap.h
=> Add MapType enum to RPG::TreeMap

src/inireader.cpp, src/reader_struct.cpp, src/reader_util.h, src/writer_xml.cpp
=> Fix some warnings

src/ldb_equipment.cpp, src/ldb_reader.cpp, src/lmt_reader.cpp, src/lmu_reader.cpp, src/lsd_reader.cpp
Forgot the binary flag 👎 
Also fixes a parsing error in RPG::Equipment detected by @20kdc
=> Fix lcf parsing under Windows

generator/csv/fields.csv, generator/generate.py, src/generated/ldb_actor.cpp, src/generated/ldb_class.cpp, src/generated/lsd_chunks.h, src/generated/lsd_saveactor.cpp, src/generated/rpg_actor.h, src/generated/rpg_class.h, src/generated/rpg_saveactor.h, src/reader_lcf.cpp, src/reader_lcf.h, src/rpg_setup.cpp, src/writer_lcf.cpp, src/writer_lcf.h
and changed the initialisation to match @20kdc observations.
This breaks compiling of the Player (Build failure issues are coming \*g\*):
```diff
diff --git a/src/game_actor.cpp b/src/game_actor.cpp
index c97415c2..c6c62242 100644
--- a/src/game_actor.cpp
+++ b/src/game_actor.cpp
@@ -940,7 +940,7 @@ void Game_Actor::ChangeBattleCommands(bool add, int id) {
GetData().battle_commands.clear();
}
else {
-		std::vector<uint32_t>::iterator it;
+		std::vector<int32_t>::iterator it;
it = std::find(GetData().battle_commands.begin(), GetData().battle_commands.end(), id);
if (it != GetData().battle_commands.end())
GetData().battle_commands.erase(it);
```
=> Change battle_commands type to vector<int32_t>

src/rpg_fixup.cpp
Fix https://github.com/EasyRPG/Player/issues/1409
=> Remove "Fixup" for class_id

generator/csv/fields.csv, src/generated/lmu_chunks.h, src/generated/lmu_map.cpp, src/generated/rpg_map.h
Adds a new chunk.
Is `save_count_2k3e` an appropriate name? If not let me know what you think might be better.
=> Add Map Chunk 0x5A

src/ini.cpp, src/ini.h, src/inireader.cpp, src/inireader.h, src/ldb_equipment.cpp, src/ldb_eventcommand.cpp, src/reader_lcf.cpp, src/reader_lcf.h, src/reader_struct.h, src/reader_struct_impl.h, src/rpg_setup.cpp
- Format (mostly newlib-related)
- Unused Parameters
=> Resolve some warnings

src/reader_util.cpp
that's some problem with the data file but can't tell you why.
There is a way to debug print the datafile stuff with UDATA_DEBUG but this gives a build error xD
=> Handle error in Unicode normalization

generator/csv/fields.csv, src/generated/lsd_chunks.h, src/generated/lsd_saveinventory.cpp, src/generated/rpg_saveinventory.h
* timerN_secs -> timerN_frames
* Add comments for all timer chunks
=> Rename timer chunks

generator/csv/fields.csv, src/generated/lsd_chunks.h, src/generated/lsd_saveeventexecframe.cpp, src/generated/lsd_saveeventexecstate.cpp, src/generated/rpg_saveeventexecframe.h, src/generated/rpg_saveeventexecstate.h, src/reader_struct.h
Saves space and removes ugly code from https://github.com/EasyRPG/Player/pull/1739
=> Interpreter state chunk fixes

generator/csv/fields.csv, generator/generate.py, generator/templates/rpg_header.tmpl, src/generated/lsd_chunks.h, src/generated/lsd_saveinventory.cpp, src/generated/rpg_actor.h, src/generated/rpg_class.h, src/generated/rpg_commonevent.h, src/generated/rpg_enemy.h, src/generated/rpg_eventpage.h, src/generated/rpg_item.h, src/generated/rpg_moveroute.h, src/generated/rpg_saveactor.h, src/generated/rpg_saveeventexecframe.h, src/generated/rpg_saveinventory.h, src/generated/rpg_savesystem.h, src/generated/rpg_skill.h, src/generated/rpg_system.h, src/generated/rpg_troop.h, src/generated/rpg_trooppage.h
https://github.com/EasyRPG/Player/pull/1798
=> Change items_size -> item_ids count field

CMakeLists.txt, README.md, configure.ac
=> liblcf 0.6.1

generator/csv/fields.csv, src/generated/lsd_saveinventory.cpp, src/generated/rpg_saveinventory.h, src/rpg_setup.cpp
Depends on: https://github.com/EasyRPG/Player/pull/1850
=> Remove SaveInventory::party_size

generator/csv/enums.csv, generator/csv/fields.csv, src/generated/lsd_chunks.h, src/generated/lsd_savepicture.cpp, src/generated/rpg_enums.cpp, src/generated/rpg_savepicture.h, src/rpg_setup.cpp
Also add comments to picture chunks
Depends on: https://github.com/EasyRPG/Player/pull/1948
=> Improve Picture LSD chunks

generator/csv/fields.csv, src/generated/lsd_chunks.h, src/generated/lsd_saveactor.cpp, src/generated/rpg_saveactor.h, src/rpg_fixup.cpp, src/rpg_setup.cpp
Depends on: https://github.com/EasyRPG/Player/pull/2032
This is an event transparency that has the same values as
SaveMapEventBase::transparency.
=> Rename SaveActorInfo sprite_flags -> transparency

src/flag_set.h
* initializer_list constructor is broken for enum classes
* Add a few more bitset methods
A few small bug fixes, would be good to get this one in soon.
=> Minor FlagSet fixes and improvements

src/encoder.cpp, src/reader_util.cpp, src/writer_xml.cpp
It took a bit longer than expected to get to this, but I finally removed the now unneeded Amiga workarounds.
=> Amiga cleanup

src/reader_struct.h
=> Fix gcc5 build

generator/csv/enums_easyrpg.csv, src/generated/lcf/rpg/eventcommand.h
nothing fancy, just adds 3 more commands.
That is likely the last PR about ManiacPatch to liblcf.
As BingShan started to write there own engine supporting more than this without sourcecode access makes no sense.
=> Add more ManiacPatch commands

generator/csv/fields.csv, src/generated/lcf/lsd/chunks.h, src/generated/lcf/rpg/savesystem.h, src/generated/lsd_saveactor.cpp, src/generated/lsd_savesystem.cpp, src/generated/rpg_savesystem.cpp, src/rpg_setup.cpp
Renaming this again to show it's known function
https://github.com/EasyRPG/Player/issues/1849#issuecomment-684122673
=> Rename message_active -> event_message_active

generator/csv/constants.csv, generator/csv/fields.csv, generator/csv/functions.csv, generator/generate.py, src/generated/lcf/rpg/saveactor.h, src/generated/lcf/rpg/saveinventory.h, src/generated/lcf/rpg/savemapevent.h, src/generated/lsd_saveactor.cpp, src/generated/rpg_saveactor.cpp, src/lsd_reader.cpp, src/rpg_fixup.cpp, src/rpg_setup.cpp
Depends on #396 
Depends on https://github.com/EasyRPG/Player/pull/2339
=> Remove SaveActor Fixup And Setup

src/reader_lcf.cpp, src/writer_lcf.cpp
The old one was optimized away
This generates worse code but as this is only used during Load and Save the negative speed impact can be ignored
=> Change Double BigEndian swap code

generator/csv/enums.csv, generator/csv/enums_easyrpg.csv, generator/csv/fields.csv, src/generated/lcf/lsd/chunks.h, src/generated/lcf/rpg/eventcommand.h, src/generated/lcf/rpg/savemapinfo.h, src/generated/lcf/rpg/savepartylocation.h, src/generated/lsd_savemapinfo.cpp, src/generated/lsd_savepartylocation.cpp, src/generated/rpg_savemapinfo.cpp, src/generated/rpg_savepartylocation.cpp
As discussed in the issue this makes it more clear what is a "number of steps" and what is "a rate".
There is also "total_encounter_rate" which is the acumulated rate while walking (to decide when its time for an encounter).
Fix #265
------
Besides added the remaining Maniac Patch event commands just for completeness
=> Encounter Rate/Steps Chunk Renaming

src/reader_lcf.cpp, src/reader_struct.h, src/writer_lcf.cpp
Resolve int warning (mostly on 3DS)
=> Fix building for Android
