EasyRPG/liblcf

- configure.ac
Reword the help message a bit, to explicitly tell what it is used for
> Fix autotools warning when using '--disable-icu'

- Makefile.am
Autotools do not substitute CFLAGS for CXXFLAGS. This causes problems,
when we have the headers not in /usr/include (e.g. Wii)
> fix passing pkg-config flags

- src/reader_util.cpp
No idea if this also fixes saving in emscripten... but is possible
Should fix saving when the encoding was specified in the INI (why was this never noticed) (fixes EasyRPG/Player#465).
> dst_enc wasn't converted to the proper names ICU/iconv expect

- src/reader_util.cpp
This function is used to use the encoding based on system locale when automatic detection fails and there is no manual encoding set. However, libstdc++ locale support is not complete on OS X and will emit a runtime error when trying to call locale functions. The alternate libc++ runtime supports it properly, but it is supported since Mac OS X 10.7. Because Player currently runs on 10.5 and links with libstdc++, the locale code is disabled to prevent the runtime error.
> OS X: Skip system locale detection

- src/reader_util.cpp
Until now, when a conversion was failing only returns an empty string as a result.
With this change, when a conversion failure occurs it will print the reason in the stderr.
> ICU: print encoding conversion error codes to stderr

- generator/csv/fields.csv
- generator/csv/setup.csv
- src/generated/rpg_mapinfo.cpp
- src/generated/rpg_savepartylocation.cpp
- src/generated/rpg_savepartylocation.h
- src/generated/rpg_savescreen.cpp
- src/generated/rpg_savescreen.h
- src/rpg_fixup.cpp
This fixes a bug where using lcf2xml would corrupt the MapTree file, thanks to elsemieni for reporting it.
> Force MapInfo.type to appear and remove unnecessary Fixups

- generator/csv/fields.csv
- src/generated/ldb_animationcelldata.cpp
- src/generated/ldb_chunks.h
- src/generated/rpg_animationcelldata.cpp
- src/generated/rpg_animationcelldata.h
Let's break the API again :D
This is a really bad one, because this results in completly wrong tone values being used in animations.
Also rename priority to valid, only valid cells are rendered.
> AnimationCellData fixes

- generator/csv/fields.csv
- src/generated/lsd_chunks.h
- src/rpg_setup.cpp
This fixes a bug where the player can walk over unpassable tiles, found in map 137 of The Gray Garden (thanks Mr.Faq2014 for reporting it) and map 342 of OFF.
> Fix default passable_data_upper

- generator/csv/fields.csv
- generator/generate.py
- src/generated/lsd_saveeventdata.cpp
- src/generated/lsd_saveevents.cpp
- src/generated/rpg_saveeventdata.cpp
- src/generated/rpg_saveeventdata.h
- src/generated/rpg_saveevents.cpp
- src/generated/rpg_saveevents.h
- src/reader_struct.h
Instead of replacing all generated files each time generator.py is run, it'll replace now only files with changes by comparing them with a temporal generated file. That way, the compiler won't have to rebuild the whole project.
> Improve generator and a couple bug fixes

- src/reader_util.cpp
liblcf will use C++11 in future commits and Player already do, so old libstdc++ 4.2.1 is not working anymore
Build with clang and link with newer libstdc++, e.g. build g++ 5.2 and use its library to support older OS X versions because OS X clang's libc++ dropped OS X support < 10.7.
> OS X: drop workaround for the old libstdc++ from Apple SDK

- src/data.cpp
Required by the Game Browser to get rid of System changes of the previous launched game
> Clear all database data in Data::Clear

- src/reader_util.cpp
The new Android version does still not compile... but here is a compile fix for liblcf ^^
> Disable std::locale for Android (unsupported by NDK)

- src/ldb_eventcommand.cpp
This should Fix https://github.com/EasyRPG/Player/issues/556
Can anybody else confirm this? Delete your old savegames, if they are already corrupted it won't help :D
Please also test: Save a game in the house with 1252 encoding. Then load it with 932 and save it.
It should still work (ICU substitutes invalid codepoints silently), at least for me.
> Correctly calculate size of RPG::EventCommand

- src/reader_util.cpp
Fixes EasyRPG/Player#649
ICU from toolchains will need to be rebuilt to make this update work properly.
After updating toolchains also closes EasyRPG/Player#746
> Change Korean and Japanese encodings to fix file finding errors

- generator/csv/enums.csv
- generator/csv/fields.csv
- src/generated/lsd_chunks.h
- src/generated/lsd_savesystem.cpp
- src/generated/rpg_savesystem.h
Active/Wait field for RPG2k3 battle
> Add Atb mode field

- src/rpg_fixup.cpp
…only an issue when loading a RPG_RT save. Fixes EasyRPG/Player/issues/600
Player#600
> SaveSystem fixup did not reload all music

- generator/csv/fields.csv
- generator/csv/setup.csv
- src/generated/lsd_chunks.h
- src/generated/rpg_saveactor.h
- src/reader_struct.h
- src/rpg_fixup.cpp
This fixes problems with the savegame sent by K風鈴 (negima.0824@)
It doesn't load in RPG_RT but looks like a RPG_RT savegame. No idea what happened, the pending field has a strange size. Also the Actor IDs are wrong.
reader_struct realigns now the read pointer when the size is incorrect and shows an error message on the console when this happens.
> Make reader_struct more fault tolerant and SaveActor::Fixup

- builds/vs2015/PropertySheet.props
I'm also currently switching the toolchain.
This adds a minor inconvenience to the user: They have to install the VS2015 runtime (not sure if it's distributed via windows update) once. They probably have an app already that did this for them.
This adds UWP support and makes the exe smaller.
> MSVC: Switch to dynamic C runtime

- src/rpg_fixup.cpp
This fixes a crash when loading some save files since EasyRPG/Player#979.
> Fix up SaveMapInfo.chipset_id value when equal or less than 0

- src/reader_util.cpp
This should fix an issue with some Simplified Chinese games which encoding is not detected as codepage 936. Current custom stripped icudata does not include some aliases but detection still works and return them. This fixes a fatal error while trying to load some games, according to Android reports.
Fixes #187.
> Use proper internal encoding name for detected GB18030

- generator/csv/fields.csv
- src/generated/rpg_battleranimationextension.h
...Otherwise RPG2k3 games fail that use the first battle animation in "Animation 2"
Fixes EasyRPG/Player#1073
> Change default value for animation_id of BattlerAnimationExtension to 1

- src/ldb_eventcommand.cpp
- src/reader_lcf.cpp
> Fix #194 (heap corruption) and #196 (LcfWriter writing incorrect strings)

- src/ldb_eventcommand.cpp
- src/reader_lcf.cpp
Removed the asserts and changed the error handling a bit because the broken event commands are reallllly bad and result in an assert when opening Scene_load or Scene_Save otherwise :(
Fixes EasyRPG/Player#1149.
> Fix savegame corruption introduced in 5abb593d

- src/rpg_setup.cpp
This is neccessary to allow setting the initial font in the database, needed for https://github.com/EasyRPG/Player/pull/1143
> Initialise font_id

- src/reader_util.h
Helper func to make accesing 1-based arrays easier.
Heavily used in my sanity check branch: https://github.com/Ghabry/easyrpg-player/tree/sanitycheck
Must be in the header otherwise the template is not instantiated when used in Player :/
> Add new function GetElement to ReaderUtil

- builds/cmake/CMakeLists.txt
- src/reader_struct.cpp
Like RPG::Save, RPG::Database has one 0-byte too much.
Merged RPG::Save & Database logic because I understood in the meanwhile how templates + type_traits work ;)
No idea if this is related to #196 
Now lcf2xml is finally more usable \o/
Better diff:
```diff
+template<typename T>
+typename std::enable_if<std::is_same<T, RPG::Save>::value ||
+		std::is_same<T, RPG::Database>::value>::type
+conditional_zero_writer(LcfWriter&) {
+	// no-op
+};
+
+template<typename T>
+typename std::enable_if<!std::is_same<T, RPG::Save>::value &&
+						!std::is_same<T, RPG::Database>::value>::type
+conditional_zero_writer(LcfWriter& stream) {
+	stream.WriteInt(0);
+};
+
template <class S>
void Struct<S>::WriteLcf(const S& obj, LcfWriter& stream) {
S ref = S();
int last = -1;
for (int i = 0; fields[i] != …
```
> Fix ldb writing

- generator/csv/fields.csv
- src/generated/rpg_savesystem.h
- src/rpg_fixup.cpp
Fix https://github.com/EasyRPG/Player/issues/1230
This results in wrong tiling in the GameBrowser.
Patch for GameBrowser:
```diff
diff --git a/src/scene_gamebrowser.cpp b/src/scene_gamebrowser.cpp
index 1ce12b47..99e292ad 100644
--- a/src/scene_gamebrowser.cpp
+++ b/src/scene_gamebrowser.cpp
@@ -41,6 +41,7 @@ Scene_GameBrowser::Scene_GameBrowser() {
void Scene_GameBrowser::Start() {
Game_System::SetSystemName(CACHE_DEFAULT_BITMAP);
+	Game_System::SetMessageStretch(RPG::System::Stretch_stretch);
CreateWindows();
Player::FrameReset();
}
```
> When message stretch is missing in the savegame use db value

- src/reader_util.cpp
These small changes (just adding #include <stdio.h> to 2 files) are required for GCC 4.8.x, which happens to be the default GCC version for the GCW0. (Yes, they're still stuck with that old version)
Without this pr, i get undefined references to fprintf.
> Fixes for GCC 4.8.x

- src/inireader.cpp
Currently not used by our code but in the filesystem code.
Buffer was not properly terminated.
And replaced the code with strncpy because that's much easier.
> Fix incorrect string handling of istream ini reader

- generator/csv/fields.csv
- src/generated/ldb_chunks.h
- src/generated/ldb_state.cpp
- src/generated/rpg_state.h
Exchange State->hp_change_map_steps and State->hp_change_map_val, and State->sp_change_map_steps and State->sp_change_map_val.
Problem: The data saved in each pair was supposed to be in the other.
> Exchange State's HP and SP map damage data (val <-> steps)

- src/reader_lcf.cpp
In reader_lcf.cpp stdio.h only got included when NDEBUG was defined, but it should be the other way around.
> Include stdio unconditionally in reader_lcf.cpp

- src/reader_lcf.cpp
- src/reader_util.cpp
- src/writer_xml.cpp
The library now builds for MorphOS and AmigaOS4 with autotools.
>  Make liblcf compile on MorphOS and AmigaOS4 

- src/reader_struct.h
Fixes a warning with `vector<bool>` bit reference and `%d` in printf.
> Fix warnings with LCF_DEBUG_TRACE

- src/reader_struct.cpp
reader_struct doesn't call Actor::Setup() to properly default the initial and final levels. The result is that liblcf writes some bytes where it shouldn't.
This adds a DefaultStruct<T>() wrapper which lets you customize how a default object is created. For most it's just a constructor, but for `Actor` you need to call `Setup()`.
Part of #234
> Call Actor::Setup() when writing ldb file

- generator/csv/fields.csv
- src/generated/rpg_terrain.h
Should also fix bugs in Player where terrain defaults to 0,0,0 and actors are ontop of each other.
> Correct defaults for Terrain grid a/b/c

- src/reader_struct.cpp
Towards addressing #249 
This one successfully parses the Devil and Angel ldb. When I copy it, the chunk for the corrupted animation is different, but everything else in the database is a perfect match.
This and other games like like it should load and be playable now in Player.
This doesn't attempt to emulate how rm2k/3 interprets the corrupted chunk.
> Detect corrupted chunks and reset the parser

- src/rpg_fixup.cpp
If the chunk name is an empty string, it means default the entire chunk to
ldb system, not just the name. That includes name, tempo, volume, balance, etc..
Fixes an issue in Player https://github.com/EasyRPG/Player/issues/985 where battle start SFX tempo was reset to 100 when loading saved games.
> Fix how SaveGame Music and sfx are loaded

- src/ldb_reader.cpp
- src/ldb_reader.h
- src/lmu_reader.cpp
- src/lmu_reader.h
- src/lsd_reader.cpp
- src/lsd_reader.h
Depends on: #264
This patch changes *_Reader::Save() to automatically increment `save_count` before writing the file.
There is a new `SaveOpt::eNoIncSaveCount` you can pass to suppress this behavior.
I also added `SaveOpt::eNoUdate` value which is intended to combine all of the `SaveOpt`'s required for copying lcf files without modifications. We should use this `SaveOpt` for our testing liblcf.
This will fix bugs in Player and Editor related to save counts.
>  Increment save counts when writing LDB, LMU, and LSD 

- Makefile.am
- builds/liblcf-config.cmake.in
Fixes an issue where an old cmake version (<3.10) will not compile
Player, because the needed EXPAT::EXPAT target is not available.
> Add cmake config to autotools-based installs

- generator/csv/enums.csv
- generator/csv/fields.csv
- src/generated/lsd_chunks.h
- src/generated/rpg_enums.cpp
- src/generated/rpg_saveactor.h
- src/rpg_setup.cpp
Changed it to an enum. The values I use are:
* 0 - front
* 1 - back
How did we come up with -1 meaning front, 1 back, and 0 being a meaningless default? Since the row chunk is not present in save data when defaulted, there doesn't seem anyway to know what the front value is in `RPG_RT` without looking at process memory, but I can't see why it would be -1.
> Fix SaveActor::row

- CMakeLists.txt
- Makefile.am
- builds/vs2015/liblcf.vcxproj
- src/encoder.cpp
- src/encoder.h
- src/reader_lcf.cpp
- src/reader_lcf.h
- src/reader_util.cpp
- src/scope_guard.h
- src/writer_lcf.cpp
- src/writer_lcf.h
Avoids memory allocations in many cases, especially when string is small.
> Optimize String Parsing routines

- CMakeLists.txt
- Makefile.am
- builds/vs2015/liblcf.vcxproj
- generator/csv/constants.csv
- generator/csv/fields.csv
- generator/generate.py
- generator/templates/rpg_header.tmpl
- generator/templates/rpg_source.tmpl
- src/generated/rpg_savepartylocation.cpp
- src/generated/rpg_savepartylocation.h
- src/generated/rpg_state.cpp
- src/generated/rpg_state.h
Towards fixing https://github.com/EasyRPG/Player/issues/1516
Also adds panning constants, so that the default pan values don't need to be duplicated between player and liblcf.
> Add support for generated constants in RPG:: classes

- src/reader_util.cpp
- src/reader_util.h
[#1530](https://github.com/EasyRPG/Player/issues/1530) and probably [#1383](https://github.com/EasyRPG/Player/issues/1383) and [#839](https://github.com/EasyRPG/Player/issues/839) in Player, by implementing normalization in place of lower-casing per @Ghabry's patch in [#839](https://github.com/EasyRPG/Player/issues/839).
Requires more thorough testing, but is confirmed to work against the Yume2kki example in [#1530](https://github.com/EasyRPG/Player/issues/1530).
***
Also needs to be tested that it doesn't break everything on [non-Mac platforms which use NFC as opposed to NFD](https://gist.github.com/JamesChevalier/8448512).
> Composite Characters Fix

- generator/csv/enums.csv
- src/generated/rpg_eventpage.h
This exists in my version of rm2k3e. No idea what it does yet, but it's missing from our enums.
> Add rm2k3 step_frame_fix animation_type

- src/reader_util.cpp
This amends #292 , works now properly on Windows
> Create icu::UnicodeString with UTF-8 codepage, fixes normalize on Windows

- src/reader_util.cpp
When LCF_SUPPORT_ICU is not defined during compilation (ICU support is disabled),
there's a compilation error due to the fact that std::transform is only referenced in algorithm.
> Fix compilation error when LCF_SUPPORT_ICU is not defined in reader_util.cpp

- generator/csv/fields.csv
- src/generated/lsd_chunks.h
- src/generated/lsd_savemapevent.cpp
- src/generated/rpg_savemapevent.h
This is the flag used to say an event is waiting for
foreground execution.
As described by Cherry in https://github.com/EasyRPG/Player/issues/1247
For `waiting_execution` chunk, simply create 2 autostart events with
```
OpenSaveMenu
```
The second event will have the flag set, while the first one (currently executing) does not.
For the `trigger_by_decision_key` chunk. Change the above events to trigger type `action`, `touch`, and/or `collision` and talk to them with the decision key. The chunk will be set in the save data.
> Fix MapEvent  waiting and trigger chunks

- generator/csv/fields.csv
- src/generated/rpg_savemapeventbase.h
Fix EasyRPG/Player#1650
The only way to trigger this is by manually killing the chunk in a hex editor or by saving with Player 0.5.4 which omits the chunk and assumes 4 as default (the chunk is persitent, even when defaulted). Now the hero has normal speed after loading an old save.
Guess this was changed by accident during refactor because the Move speed in the LDB has 3 as default... Not very consistent.
> Savegame move speed default is 4 and not 3

- CMakeLists.txt
- Makefile.am
- generator/csv/fields_easyrpg.csv
- generator/csv/structs_easyrpg.csv
- generator/generate.py
- src/generated/lsd_chunks.h
- src/generated/lsd_save.cpp
- src/generated/lsd_saveeasyrpgdata.cpp
- src/generated/rpg_save.h
- src/generated/rpg_saveeasyrpgdata.h
- src/lsd_reader.cpp
- src/lsd_reader.h
This adds a new EasyRpg chunk to the savegame with one field: version.
I picked 0xc8 (200) because Cherry asked us to look at the decimals and RPG_RT starts at 0x64 (100)
Patch for the Player site, wrapping our compatibility hack in a if-block.
```
diff --git a/src/player.cpp b/src/player.cpp
index 64e3ea35..e833188a 100644
--- a/src/player.cpp
+++ b/src/player.cpp
@@ -812,11 +812,12 @@ static void OnMapSaveFileReady(FileRequestResult*) {
// Compatibility hack for pre 0.6 EasyRPG Player saves.
// Old savegames accidentally wrote animation_type as
// continuous for all events.
-	Main_Data::game_player->SetAnimationType(Game_Character::AnimType::AnimType_non_continuous);
-	Game_Map::GetVehicle(Game_Vehicle::Boat)->SetAnimationType(Game_Character::AnimType::AnimType_non_continuous);
- …
```
> Add Easyrpg savegame chunk

- src/encoder.cpp
On other platforms stdlib.h gets included by other headers, but not on MorphOS, where atoi doesn't get declared, so I added an explicit include in encoder.cpp.
> MorphOS build fix

- src/encoder.cpp
This change, alongside ccawley2011/liblcf@9b2b46f, are needed when building liblcf on RISC OS.
> Add missing <cstdio> include

- generator/csv/fields.csv
- src/generated/ldb_chunks.h
- src/generated/ldb_item.cpp
- src/generated/ldb_skill.cpp
- src/generated/rpg_item.h
- src/generated/rpg_skill.h
The original name was not descriptive and is almost the same
as state_effects, which is the state array.
> Rename 2k3 Skill/Item state_effect -> reverse_state_effect

- generator/csv/fields.csv
- src/generated/lsd_chunks.h
- src/generated/lsd_savevehiclelocation.cpp
- src/generated/rpg_savevehiclelocation.h
This chunk must not exist, because vehicles don't have
original move routes like events do.
Fix: #304
> Remove SaveVehicleLocation::original_move_route_index

- generator/csv/fields.csv
- src/generated/lsd_saveactor.cpp
Fix: https://github.com/EasyRPG/Player/issues/1789
It's not entirely clear to me whether this logic belongs in liblcf or Player. It seems that the fact that we use the `SaveActor` struct directly in Player (vs copying the data out to another structure), and therefore needing this adjustment is an implementation detail of Player.
Thoughts?
> Fix SaveActor Flags

- generator/csv/fields.csv
- src/generated/lsd_chunks.h
- src/generated/lsd_savevehiclelocation.cpp
- src/generated/rpg_savemapeventbase.h
- src/generated/rpg_savevehiclelocation.h
Screen flash chunks are not present when they are 0.
Event flash chunks are present for all values 0 to 32, so default
must be -1.
32 was tested using hex editor.
> Fix defaults for event flash colors + vehicle sprites

- generator/csv/fields.csv
- src/generated/rpg_savesystem.h
- src/rpg_fixup.cpp
- src/rpg_setup.cpp
When graphics_name is empty, it means that graphics_name,
message_stretch, and font_id all fallback to the database values.
If graphics_name is non-empty, all 3 parameters values are taken
literally.
Depends on: https://github.com/EasyRPG/Player/pull/1842
> Fix SystemGraphics save chunks

- generator/csv/enums_easyrpg.csv
- generator/generate.py
- src/generated/rpg_eventcommand.h
SetMousePositon surprisingly doesn't add a new chunk to the savegame, which means the offset is not stored.
Not fully sure what "EndLoading" is supposed to do, doesn't match with the documentation. waiting for a response on twitter.
> Add Maniac Patch Event commands

- generator/csv/fields.csv
- src/generated/lsd_saveeventexecframe.cpp
Fixes "List index has exceeded its valid range (0)" crash
when loading Player saves in RPG_RT.
> Crash Fix: SaveEventExecFrame::commands size field always present if default

- CMakeLists.txt
- Makefile.am
- generator/generate.py
- generator/templates/fwd_header.tmpl
- src/generated/fwd_struct_impl.h
- src/lmt_rect.cpp
- src/reader_struct_impl.h
Fix: #221
Re-implementation of #290, this time with autogenerated declarations.
Unfortunately, this is still broken with MSVC 2019, so I put ifdefs around it.
> Fix clang template warnings

- CMakeLists.txt
To make this better extensible "check" is now not touched anymore (just created when missing).
test_runner target is changed to test_runner_lcf and check_lcf attaches itself to check as a dependency.
the dependency tree is now "check <- check_lcf <- test_runner_lcf"
> CMake: Prevent conflicts in the test runner

- CMakeLists.txt
Using GNUInstallDirs to always have an absolute path regardless of the
user input: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
---
Fixes issue mentioned in https://github.com/EasyRPG/Player/issues/1753#issuecomment-527319815
`CMAKE_INSTALL_{LIB,INCLUDE}DIR` can be used both with a relative path (`lib64`, `include`) or absolute (`/usr/lib64`, `/usr/local/include`, etc.), and in the latter case the previous logic is broken.
One drawback of this change is that it no longer makes use expanding `${exec_prefix}`, but to be honest I've never seen any real-life use case for that in `.pc` files. There might be on other platforms than Linux/*BSD though.
---
Not directly related, but since you put liblcf headers in a `liblcf` folder, I would advise for using `#include …
> pkgconfig: Fix support for absolute lib and include dirs

- CMakeLists.txt
- Makefile.am
I'd like to get this nastiness:
https://github.com/EasyRPG/liblcf/blob/master/src/writer_xml.cpp#L12
The problem is what `-std=c++11` defines `__STRICT_ANSI__` which causes a lot of functions to go undeclared on AmigaOS4. I made this a separate PR in case it causes any problems.
> Enable the GNU extensions

- CMakeLists.txt
- Makefile.am
- README.md
- configure.ac
- tools/lcf2xml.cpp
Don't review lcf2xml.cpp. The file is copied as-is. If you dislike it, submit patches later.
> Migrate lcf2xml to liblcf

- .editorconfig
This is a modern approach to modelines and such.
This is not about linting, just to set sane editor defaults.
For more information, see https://editorconfig.org
> Add editorconfig file to avoid whitespace problems

- CMakeLists.txt
- Makefile.am
- README.md
- src/lcf/span.h
- src/lcf/string_view.h
- src/lcf/third_party/span.h
- src/lcf/third_party/string_view.h
- tests/span.cpp
- tests/string_view.cpp
I'm pulling these out of the other refactor PRs so we can review concerns about how to move forward with these 3rd party implementations and also so I can use this as a base for Player PR's depending on these.
If the String refactor will take a long time to review, I would rather this gets reviewed and in sooner.
Getting this in also means we can compile some of https://github.com/EasyRPG/Player/pull/2280 against current master and review it sooner.
> Add StringView and Span

- src/generated/lcf/rpg/fwd.h
There was a bug in fwd.h from previous PR. The generated header included in the PR was an older version. This regenerates the header and fixes it.
> Fix generated fwd.h header

- CMakeLists.txt
- Makefile.am
- generator/csv/fields.csv
- generator/generate.py
- src/generated/lcf/rpg/item.h
- src/generated/lcf/rpg/skill.h
- src/generated/lcf/rpg/troop.h
- src/generated/ldb_item.cpp
- src/generated/ldb_skill.cpp
- src/generated/ldb_troop.cpp
- src/lcf/dbbitarray.h
- src/lcf/reader_lcf.h
- src/lcf/writer_lcf.h
- src/reader_lcf.cpp
- src/reader_struct.h
- src/reader_xml.cpp
- src/writer_lcf.cpp
- src/writer_xml.cpp
- tests/dbbitarray.cpp
Depends on #379 
I've added support for `DBBitArray` as a replacement for `vector<bool>`. This data structure again uses the same memory allocation strategy as `DBString` and `DBArray`.
| Game | Ldb Size | #379 | This PR |
| -- | -- | -- | -- |
| HH3 | 16MB |  68.7 MB | 68.5MB |
| Heroes Realm | 27MB |  143.3 MB | 143.3MB | 
| Violated Heroine | 11MB | 41.4 MB | 40.6MB |
| Yume 2kki | 1.4MB | 4.9 MB | 4.8MB |
The overall savings here are pretty modest Lets look more closely at hh3's database with certain structs compiled out. This game has 850 skills and 2280 items.
Memory usage:
| | All except troops & common events | Only Items | Only Skills |
| -- | -- | -- | -- |
| #379 | 3.2MB | 936.5KB | 354.3KB |
| This PR | 2.9MB | 651.8KB | 302.0KB |
So overall, we see a good % reduction in the …
> Optimize memory with DBBitArray

- src/dbarray.cpp
- src/lcf/dbarrayalloc.h
- src/lcf/span.h
- src/lcf/string_view.h
> Force nonstd string_view and span to fix C++17/20 interop

- src/dbarray.cpp
- src/lcf/dbarrayalloc.h
C++17 made constexpr implicity inline which gives linker errors here because lcf is compiled as C++14 but Editor is C++17
see http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0386r2
Fixes linking with g++ and makes clang++ ASAN happy.
> make _empty_buf const instead of constexpr

- generator/csv/functions.csv
- src/generated/lcf/rpg/actor.h
- src/lcf/writer_lcf.h
- src/lcf/writer_xml.h
- src/ldb_reader.cpp
- src/lmt_reader.cpp
- src/lmu_reader.cpp
- src/lsd_reader.cpp
- src/reader_flags.cpp
- src/reader_struct.h
- src/reader_struct_impl.h
- src/rpg_setup.cpp
- src/writer_lcf.cpp
- src/writer_xml.cpp
Preparation for removing globals from liblcf. This change only moves `lcf::Data` out to the edges. Player and Editor are not affected by this.
Next PR will remove `lcf::Data`
TBD:
> Move lcf::Data out of parser implementations

- CMakeLists.txt
- Makefile.am
- generator/csv/constants.csv
- generator/csv/fields_easyrpg.csv
- generator/csv/functions.csv
- generator/generate.py
- generator/templates/rpg_header.tmpl
- src/generated/lcf/ldb/chunks.h
- src/generated/lcf/rpg/terms.h
- src/generated/ldb_terms.cpp
- src/generated/rpg_terms.cpp
- src/rpg_terms.cpp
This PR adds the following database settings:
- Term 200: Item number separator
- Term 201: Skill cost separator
- Term 202: Equipment window arrow
- Term 203: Status scene Name
- Term 204: Status scene Class
- Term 205: Status scene Title
- Term 206: Status scene Condition
- Term 207: Status scene Front
- Term 208: Status scene Back
- Term 209: Order scene Confirm
- Term 210: Order scene Redo
- Term 211: RPG Maker 2003 battle monster Double Attack notification
- Term 212: RPG Maker 2003 battle monster Defend notification
- Term 213: RPG Maker 2003 battle monster Observe notification
- Term 214: RPG Maker 2003 battle monster Charge notification
- Term 215: RPG Maker 2003 battle monster Self-Destruct notification
- Term 216: RPG Maker 2003 battle monster Escape notification
- Term 217: …
> Make some hardcoded terms customizable

- builds/liblcf-config.cmake.in
Detected by Android because it forces me to use this version...
> CMake 3.8: Fix liblcf-config.cmake

- generator/csv/enums_easyrpg.csv
- generator/csv/fields_easyrpg.csv
- src/generated/lcf/ldb/chunks.h
- src/generated/lcf/lsd/chunks.h
- src/generated/lcf/rpg/enemy.h
- src/generated/lcf/rpg/eventpage.h
- src/generated/lcf/rpg/saveeventexecframe.h
- src/generated/lcf/rpg/savesystem.h
- src/generated/ldb_enemy.cpp
- src/generated/lsd_saveeventexecframe.cpp
- src/generated/lsd_savesystem.cpp
- src/generated/rpg_enemy.cpp
- src/generated/rpg_saveeventexecframe.cpp
- src/generated/rpg_savesystem.cpp
- src/lcf/reader_lcf.h
- src/ldb_equipment.cpp
- src/reader_lcf.cpp
- src/reader_struct_impl.h
TODO:
- ~~For ``ManiacEventInfo`` figure out what the ``was*`` things are~~
- ~~Still some unknown chunks, waiting for BingShan reponse~~
> Add Maniac patch chunks

- generator/csv/constants.csv
- generator/csv/fields_easyrpg.csv
- src/generated/lcf/ldb/chunks.h
- src/generated/lcf/rpg/item.h
- src/generated/lcf/rpg/skill.h
- src/generated/lcf/rpg/terms.h
- src/generated/ldb_item.cpp
- src/generated/ldb_skill.cpp
- src/generated/ldb_terms.cpp
- src/generated/rpg_item.cpp
- src/generated/rpg_skill.cpp
- src/generated/rpg_terms.cpp
Requirement for [Player#2502](https://github.com/EasyRPG/Player/pull/2502)
This PR adds the following database settings:
- Skill option 201 RPG Maker 2003 skill start notification
- Item option 201: Item usage message in battle
- Term 218: RPG Maker 2003 general skill start notification
- Term 219: RPG Maker 2003 general item start notification
> Make more hardcoded terms customizable

- generator/csv/fields_easyrpg.csv
- src/generated/lcf/ldb/chunks.h
- src/generated/lcf/rpg/battlecommands.h
- src/generated/lcf/rpg/item.h
- src/generated/lcf/rpg/skill.h
- src/generated/lcf/rpg/system.h
- src/generated/ldb_battlecommands.cpp
- src/generated/ldb_item.cpp
- src/generated/ldb_skill.cpp
- src/generated/ldb_system.cpp
- src/generated/rpg_battlecommands.cpp
- src/generated/rpg_item.cpp
- src/generated/rpg_skill.cpp
- src/generated/rpg_system.cpp
This PR adds the following database settings, here we can discuss which ones are useful for inclusion. If some options are unclear, then ask away!
- BattleCommands option 200: Default ATB mode
- BattleCommands option 201: Enable in-battle row command
- BattleCommands option 202: Sequential order battling
- Skill option 202: Ignore reflect state
- Skill option 203: State infliction hit rate
- Skill option 204: Attribute shift hit rate
- Skill option 205: Ignore physical rate restriction by states
- Skill option 206: Ignore magical rate restriction by states
- Skill option 207: Enable stat absorbing
- Item option 202: Maximum item count in inventory
- System option 200: Alternative EXP curve
- System option 201: Battle options
- System option 202: Maximum actor HP value
- System option 203: …
> Add custom game settings in the database

- src/lcf/ldb/reader.h
- src/lcf/lmt/reader.h
- src/lcf/lmu/reader.h
- src/lcf/lsd/reader.h
- src/lcf/reader_lcf.h
- src/lcf/reader_util.h
- src/lcf/writer_lcf.h
- src/ldb_reader.cpp
- src/lmt_reader.cpp
- src/lmu_reader.cpp
- src/lsd_reader.cpp
- src/reader_lcf.cpp
- src/reader_util.cpp
- src/writer_lcf.cpp
The first commit is not really needed for it but it makes it after 0.7 easier to replace StringView with std::string_view (C++17). This is API compatible, no changes needed to consumers.
The second commit changes the Encoding Api from Streams to a Database-handle. Because we do not operate on global objects anymore the database checked by player was always empty. This fixes it (Player loads the DB and passes it in). I also noticed that for whatever reason the language detection is better when system tab is at the beginning (maybe filenames are better than terms because they are usually unaffected by translations?)
> Improve encoding detection

- generator/csv/enums_easyrpg.csv
- generator/csv/fields_easyrpg.csv
- src/generated/lcf/ldb/chunks.h
- src/generated/lcf/rpg/actor.h
- src/generated/lcf/rpg/battlecommands.h
- src/generated/lcf/rpg/enemy.h
- src/generated/lcf/rpg/skill.h
- src/generated/lcf/rpg/state.h
- src/generated/lcf/rpg/system.h
- src/generated/lcf/rpg/terrain.h
- src/generated/ldb_actor.cpp
- src/generated/ldb_battlecommands.cpp
- src/generated/ldb_enemy.cpp
- src/generated/ldb_skill.cpp
- src/generated/ldb_state.cpp
- src/generated/ldb_system.cpp
- src/generated/ldb_terrain.cpp
- src/generated/rpg_actor.cpp
- src/generated/rpg_battlecommands.cpp
- src/generated/rpg_enemy.cpp
- src/generated/rpg_enums.cpp
- src/generated/rpg_skill.cpp
- src/generated/rpg_state.cpp
- src/generated/rpg_system.cpp
- src/generated/rpg_terrain.cpp
This PR adds the following database settings, here we can discuss which ones are useful for inclusion. If some options are unclear, then ask away!
- BattleCommands option 203: Disable RPG Maker 2003 row feature
- Actor option 201: Custom Actor AI behavior
- Actor option 202: Protected against critical hits
- Actor option 203: Increased physical attack evasion rate
- Actor option 204: Immune to attribute downshifts
- Actor option 205: Ignore enemy evasion on physical attacks
- Actor option 206: Unarmed attack hit rate
- Actor options 207 and 208: States inflicted by unarmed normal attacks
- Actor option 209: State infliction probability by unarmed normal attacks
- Actor options 210 and 211: Attributes used by unarmed normal attacks
- Actor option 212: Unarmed attack dual attack
- Actor …
> Add more custom game settings in the database

- src/lcf/enum_tags.h
Underwise this overflows for e.g. 8 bit enums with more then 128 entries (Key list)
> Enum tags: Make size field unsigned

- src/reader_util.cpp
Fix EasyRPG/Player#2786
-----------
This code could use an optimisation as in gencache where NFKC and Locale are cached but this would be more work to refactor first :)
> Normalize: Use Invariant locale (Root)

- .github/workflows/stable-compilation.yml
- generator/csv/enums.csv
- generator/csv/fields.csv
- src/generated/lcf/lsd/chunks.h
- src/generated/lcf/rpg/eventcommand.h
- src/generated/lcf/rpg/savemapeventbase.h
- src/generated/lsd_savemapevent.cpp
- src/generated/lsd_savemapeventbase.cpp
- src/generated/lsd_savepartylocation.cpp
- src/generated/lsd_savevehiclelocation.cpp
- src/generated/rpg_savemapeventbase.cpp
(Player PR follows soon)
move_route_repeated -> move_route_done
sprite_direction -> facing
sprite_transparent -> sprite_hidden
route_through -> move_route_through
Event command SpriteTransparency -> PlayerVisibility This cmd only toggles visible and hidden, not transparency
Fix #378
> Rename some chunks to make their purpose more clear

- CMakeLists.txt
Verified this now by looking in build.ninja
Player build tested on a Linux with liblcf uninstalled and on macOS.
> Amend #448. CMake: INSTALL_INTERFACE must be CMAKE_INSTALL_INCLUDEDIR

- .gitignore
- CMakeLists.txt
- builds/autoconf/liblcf-config.cmake.in
Tested now the following combinations:
- liblcf build with autotools
- liblcf build with CMake
For both static and shared.
Then compiled Player:
- CMake with liblcf autotools: Both "pkg-config" and "pkg-config --static" tested (4 builds)
- CMake with liblcf CMake (2 builds)
Everything works. This stuff is so dumb.
> CMake config: 3rd try

- CMakeLists.txt
- Makefile.am
- generator/csv/enums.csv
- generator/csv/enums_easyrpg.csv
- generator/csv/fields_easyrpg.csv
- generator/csv/flags_easyrpg.csv
- generator/csv/structs_easyrpg.csv
- generator/generate.py
- src/generated/fwd_struct_impl.h
- src/generated/lcf/lsd/chunks.h
- src/generated/lcf/rpg/fwd.h
- src/generated/lcf/rpg/saveeasyrpgdata.h
- src/generated/lcf/rpg/saveeasyrpgtext.h
- src/generated/lcf/rpg/saveeasyrpgwindow.h
- src/generated/lcf/rpg/savepicture.h
- src/generated/lcf/rpg/system.h
- src/generated/lsd_saveeasyrpgdata.cpp
- src/generated/lsd_saveeasyrpgtext.cpp
- src/generated/lsd_saveeasyrpgtext_flags.h
- src/generated/lsd_saveeasyrpgwindow.cpp
- src/generated/lsd_saveeasyrpgwindow_flags.h
- src/generated/lsd_savepicture.cpp
- src/generated/rpg_enums.cpp
- src/generated/rpg_saveeasyrpgdata.cpp
- src/generated/rpg_saveeasyrpgtext.cpp
- src/generated/rpg_saveeasyrpgwindow.cpp
- src/generated/rpg_savepicture.cpp
- src/reader_flags.cpp
- src/reader_struct.h
This is implemented with a new data structure EasyRpgWindow that contains EasyRpgText.
When we ever add our own Window event functions these will provide a good baseline.
The window has the same ID as the picture. The picture receives a new field ``easyrpg_type`` to indicate if anything is attached to the picture.
The savegame receives a new chunk "2" to the EasyRPG data: ``Array<SaveEasyRpgWindow>``.
A ``SaveEasyRpgWindow`` describes a single window. Right now only ShowStringPic can create them.
A Window has styling information and a list of texts (``SaveEasyRpgText``).
Window styling stuff: width, height, system_name, message_stretch, flags like "draw_frame".
``SaveEasyRpgText`` contains stuff like "text" (obviously), x, y, font, font size, letter spacing (unsupported), line spacing, …
> Add custom chunks required for ShowStringPicture

- generator/csv/fields_easyrpg.csv
- src/encoder.cpp
- src/generated/lcf/lsd/chunks.h
- src/generated/lcf/rpg/saveeasyrpgdata.h
- src/generated/lsd_saveeasyrpgdata.cpp
- src/generated/rpg_saveeasyrpgdata.cpp
- src/lcf/lsd/reader.h
- src/lsd_reader.cpp
This allows specifying an encoding for the savegame. Useful for the saving of translated games to prevent data loss.
Usage on Player side:
```diff
diff --git a/src/scene_save.cpp b/src/scene_save.cpp
index ca470de00..97aa49d30 100644
--- a/src/scene_save.cpp
+++ b/src/scene_save.cpp
@@ -16,6 +16,7 @@
*/
// Headers
+#include "translation.h"
#include <sstream>
#ifdef EMSCRIPTEN
@@ -124,7 +125,10 @@ bool Scene_Save::Save(std::ostream& os, int slot_id, bool prepare_save) {
Game_Map::PrepareSave(save);
if (prepare_save) {
-		lcf::LSD_Reader::PrepareSave(save, PLAYER_SAVEGAME_VERSION);
+		// When a translation is loaded always store in Unicode to prevent data loss
+		int codepage = Tr::HasActiveTranslation() ? 65001 : 0;
+
+		lcf::LSD_Reader::PrepareSave(save, PLAYER_SAVEGAME_VERSION, …
```
> Add "codepage" field to easyrpg_data

- src/lsd_reader.cpp
- src/writer_xml.cpp
Indent broke String Pictures. This shouldn't break anything as nothing else can contain linebreaks, except if you mess with the data.
Reported by @florianessl thx
> Codepage chunk 2nd try / String Picture XML Fix

- generator/generate.py
- src/generated/lcf/rpg/commonevent.h
- src/generated/lcf/rpg/encounter.h
Fixes the following build error (for Wii, g++ 13.1.0):
```
In file included from /var/lib/jenkins/workspace/liblcf-wii/src/generated/rpg_encounter.cpp:13:
/var/lib/jenkins/workspace/liblcf-wii/src/generated/lcf/rpg/encounter.h:26:17: error: 'int32_t' does not name a type
26 |                 int32_t troop_id = 0;
|                 ^~~~~~~
/var/lib/jenkins/workspace/liblcf-wii/src/generated/lcf/rpg/encounter.h:15:1: note: 'int32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
14 | #include "lcf/context.h"
+++ |+#include <cstdint>
15 | #include <ostream>
```
> Generator: Make int types available for References

- CMakeLists.txt
Needs at least CMake 3.20 to work properly
(untested)
> CMake: Fix Big endian detection when crosscompiling

- generator/csv/fields_easyrpg.csv
- src/generated/lcf/ldb/chunks.h
- src/generated/lcf/rpg/battlecommands.h
- src/generated/ldb_battlecommands.cpp
- src/generated/rpg_battlecommands.cpp
This PR adds new chunks used for features mentioned in https://github.com/EasyRPG/Player/pull/3052
> Battle 2k3: chunks for fixed battler facing direction

- src/encoder.cpp
- src/lcf/encoder.h
The defines were not correctly handled because config.h was not included
This crashed on macOS and thankfully also on 32 bit Windows where the debugger is better ;)
> Fix heap corruption in Encoder

- .github/workflows/stable-compilation.yml
- CMakeLists.txt
- builds/cmake/Modules/MiscUtils.cmake
- Better use as submodule, without install target (useful for flatpak)
- Prevent in-source builds
> Update workflow and cmakery

- generator/csv/fields_easyrpg.csv
- src/generated/lcf/lsd/chunks.h
- src/generated/lcf/rpg/savepicture.h
- src/generated/lsd_savepicture.cpp
- src/generated/rpg_savepicture.cpp
Adds the following lines inside fields_easyrpg.csv:
- current_scale_width
- current_scale_height
- finished_scale_width
- finished_scale_height
This is in preparation for adding Width/Height support into EasyRPG.
> Maniacs Feature: Add separate Width/Height parameters for scaling pictures

- CMakeLists.txt
- Makefile.am
- src/dbstring_struct.cpp
- src/encoder.cpp
- src/lcf/log_handler.h
- src/lcf/reader_xml.h
- src/ldb_equipment.cpp
- src/ldb_eventcommand.cpp
- src/ldb_parameters.cpp
- src/ldb_reader.cpp
- src/lmt_reader.cpp
- src/lmt_rect.cpp
- src/lmt_treemap.cpp
- src/lmu_movecommand.cpp
- src/lmu_reader.cpp
- src/log.h
- src/log_handler.cpp
- src/lsd_reader.cpp
- src/reader_flags.cpp
- src/reader_lcf.cpp
- src/reader_struct.h
- src/reader_struct_impl.h
- src/reader_util.cpp
- src/reader_xml.cpp
First commit: The chunk dumping during Skip didnt really work except on Windows. I finally fixed it (useful for Maniacs Patch to find unknown chunks). Also is now always on, a missing chunk is now always a bug because we know about all common ones.
Second commit: **I want your feedback here**. Before I implement this completely (is some work) please tell me if the general approach is fine for you.
I want to allow custom output handlers for lcf diagnostics. E.g. for the Player they could be written to easyrpg_log.txt. Currently they are completely lost which is bad for handling bug reports. As vital information is missing.
To redirect it library users can invoke lcf::LogHandler::SetHandler(_Handlerfunctionhere_)
> Allow redirection of lcf console messages

- generator/generate.py
Easily reproducible by introducing new values in easyrpg_fields.csv:
```
EventPage,Trigger,map_init_deferred,8
EventPage,Trigger,map_init_immediate,9
```
Depends on order though. I defined these values at line 35, right before the Maniac stuff:
`EventPage,ManiacEventInfo,*`
> Code generation fix: Specifying new values for existing enums in a separate file might overwrite existing ones

- generator/csv/fields_easyrpg.csv
- src/generated/lcf/lsd/chunks.h
- src/generated/lcf/rpg/savepartylocation.h
- src/generated/lsd_savepartylocation.cpp
- src/generated/rpg_savepartylocation.cpp
Maniac Patch has a was for scrolling screen with pixel precision.
It uses two doubles, stored inside SavePartyLocation at 0x8D and 0x8E respectively.
Sister request for https://github.com/EasyRPG/Player/pull/3245
> Maniac Patch : Adding separate camera pan speeds from Maniac Patch

- generator/csv/fields.csv
- src/generated/lcf/rpg/commonevent.h
Fixes CEs initializing with an invalid trigger type value of 0 by properly replacing it with 5 ("call" type).
> Change default CE to have the "call" trigger type

- generator/csv/fields_easyrpg.csv
- src/generated/lcf/lsd/chunks.h
- src/generated/ldb_actor.cpp
- src/generated/ldb_enemy.cpp
- src/generated/ldb_state.cpp
- src/generated/lsd_savepicture.cpp
For #484 I removed the dust from my old diff tool used in #242 and noticed that the files differ after a load-save-operation with liblcf.
A few of our custom chunks were set to _PersistIfDefault_ (always write, even when default value), so they were added to all database files processed by liblcf (e.g. lcf2xml).
This didn't damage the files but was a useless addition which increased the filesize.
Now the files are perfect again :) (= a read-write-cycle changes nothing in the files)
> Restore Bit perfect read/write ability

- CMakeLists.txt
- CMakePresets.json
- builds/cmake/CMakePresets.json.template
- builds/cmake/CMakePresetsBase.json
- builds/cmake/liblcf-config.cmake.in
- src/encoder.cpp
- src/reader_util.cpp
Ported the normalization code to the ICU C-API so looks more ugly now :sweat_smile: but C++ has no stable ABI so Microsoft decided to only provide the C part.
This _does not_ remove 3rd party ICU support. When a custom ICU library is found it has preference.
Rest is just updating of presets based on Player preset updates.
---
For now I plan to keep using the vcpkg ICU library but when I do not want to maintain this anymore I can now simply drop it.
> Support ICU library provided by Windows 10 + Preset updates

- src/lcf/scope_guard.h
Required to make the Player callback Api usable
> ScopeGuard: Allow move assignment

- src/reader_util.cpp
Sounds dumb but it works when displaying the game title for Android.
Also ignore UTF16 as this encoding cannot be correct.
> Improve encoding detection by making the string larger

- CMakeLists.txt
- Makefile.am
- README.md
- builds/cmake/liblcf-config.cmake.in
- builds/config.h.in
- configure.ac
- src/lcf/reader_util.h
- src/reader_util.cpp
- tools/lcf2xml.cpp
inih isn't used by anything in liblcf directly, relaxing this requirement and allowing it to be disabled enables outside projects to more easily integrate this library into their application.
This PR enables this while still making inih a default requirement, so the current behavior is the default one requiring no changes in existing apps (easyrpg-player)
> Don't strictly require inih

- CMakeLists.txt
- builds/cmake/liblcf-config.cmake.in
> CMake: Support legacy EXPAT Find package in the config file
